### ISSUE TITLE
Clearing after compilation losing the compiler output messages

### ISSUE THREAD

**Issue by TechnoTone** [danillouz/clean-terminal-webpack-plugin#19]
We have found that clearing the output before the compiler runs is working better for us. Instead of using the afterCompile hook, using the beforeCompile hook means we can see the errors being produced by the compiler rather than just seeing whatever is reported by webpack.

Currently, we have manually hacked the script on line 37 to change it to the beforeCompile hook, but it would be nice if this was a config option for the clean-terminal plugin.

**Comment by danillouz** [comment]
Hi Tony, thanks for opening an issue, and sorry for the late response.

I haven't used Webpack for a while, and I'm no longer familiar with its API and behavior. But I'm happy to help and add changes if that makes the package better.

However, it's a bit difficult for me to evaluate if this change would have any "unexpected/different" behavior when people would use the package with your suggested change.
If I understand correctly, the only change (in terms of output) would be that we'd also see compiler errors (if there are any), but that otherwise behavior is exactly the same. Is that right?

How would you suggest to implement this change?
Is it just changing `afterCompile` on this [line](https://github.com/danillouz/clean-terminal-webpack-plugin/blob/master/index.js#L47) to `beforeCompile`?
Or should it perhaps be made configurable?

**Comment by TechnoTone** [comment]
Hi. Yes, that's exactly what we have done locally as a "hack" so that we can see the compiler errors.

A config option would probably be better rather than change any behaviour that existing users are used to. But that would be harder to implement. I suppose if you did just change it people who wanted the original behaviour could just install the current version instead.

**Comment by danillouz** [comment]
I think the config option would be nicer as well, compared to releasing a major version with the change. Since we'd potentially have to maintain multiple versions (e.g. with fixes, etc.).
However, the plugin is super simple, so it would probably be alright going to v3.
And I guess a major version upgrade will have to happen soon anyway since Webpack v5 is coming (right?), and the current version has a peer dependency on Webpack v4.

I'll try to make some time soon, and research if the config option could be implemented easily. But if you have the time, and feel like helping out, feel free to send a PR.
